name: Sanity checks

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    sanity:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
            - name: Cache Bun dependencies
              id: cache
              uses: actions/cache@v4.0.2
              with:
                  path: ~/.bun/install/cache
                  key: "${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}"
                  restore-keys: |
                      ${{ runner.os }}-bun-
            - name: Install dependencies
              run: bun install
            - name: Run Prettier
              run: bun format
            - name: Run ESLint
              run: bun run lint
            - name: Run Tests
              run: bun test
